spring.application.name=eurekaserver

# Puerto donde se levantará el servidor Eureka
server.port=8761

# Configuración de Eureka como servidor
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


