logging:
    level:
        root: INFO
        cl.duoc.login: DEBUG
    file: 
        name: logs/login-service.log
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
