version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_login
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: login
      MYSQL_USER: vcofre
      MYSQL_PASSWORD: vcofre123
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
